# Constraints
[constraint.joint.limit]
weight = 1e9
r = 0.97

[constraint.torque.limit]
weight = 1e12
r = 1.0

[constraint.wrenchcone]
weight = 1e1

# [constraint.copbox]
# weight = 1e2
# size = [0.01, 0.01]

[constraint.frametranslation]
weight = 1e8

# Contact model
[contact.baumgarte]
gains = [0.0, 30.0]

# Impact costs
[impact.swingfoot]
weight = 1e12

# Tracking costs
[tracking.supportfoot]
weight = 1e9

[tracking.swingfoot]
min_weight = 1e6
max_weight = 1e9
ratio = [1.0, 1.0, 1.0, 0.1, 0.01, 1.0]

# [tracking.swingfoot.flyhigh]
# slope = 10.0
# weight = 1e7

# Regularization
[regularization.swingfoot]
verticalvelocity = 0.0

[regularization.freeflyer]
orientation = 5e3

[regularization.state]
position = 1e-1

[regularization.joint]
position = 1e-1
velocity = 1e-1
acceleration = 1e4
torque = 1e-1

# Final state
[final.joint]
position = 1e6
velocity = 1e2
